#!/bin/bash
# Test script - simulates behavior but can't actually press keys in this env
echo "Testing manual stop mode..."
echo ""
echo "Command: uv run voice_to_text.py --record-once"
echo "Expected behavior:"
echo "  1. Tool starts, finds keyboard device"
echo "  2. Waits 2 seconds"
echo "  3. Starts recording with 2 beeps"
echo "  4. Shows 'Press Alt+R again to stop recording'"
echo "  5. Waits for Alt+R keypress"
echo "  6. Stops recording with 1 beep"
echo "  7. Transcribes and inserts text"
echo ""
echo "With -d flag:"
echo "  Command: uv run voice_to_text.py --record-once -d 5"
echo "  Behavior: Fixed 5 second recording (no keyboard monitoring)"
echo ""
echo "NOTE: Requires input group membership:"
echo "  sudo usermod -aG input \$USER"
echo "  Then log out and back in"
